# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efed8da53e72fd32deaf2754456a540627ec2a42170b04436171c0404309aa0a71d1ffd4c07ab87ce3af8f626b63e7a67c9cf6a6ce24de72f135c10edb552776

test:
  secret_key_base: 45b50152367a49b039137e07ef5c3175a51e2981952445f1fbb5c3bbddbfc29c4427863ded3665d3384e8a72846933249fc88c7f2808e3f1adbaea988a97b90d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
